development:
  adapter: postgresql
  encoding: unicode
  database: sample_development
  pool: 5
  username: sample
  password: sample
test:
  adapter: postgresql
  encoding: unicode
  database: sample_test
  pool: 5
  username: sample
  password: sample
production:
  adapter: postgresql
  encoding: unicode
  database: sample_production
  pool: 5
  username: sample
  password: sample
